---
#
# Ansible managed
#
repository:
  description: Install subversion and create repositories on your system.
  homepage: https://robertdebock.nl/
  topics: subversion, development, ansible, molecule, tox, playbook
