---
# tasks file for subversion

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install subversion
  ansible.builtin.package:
    name: "{{ subversion_packages }}"
    state: present

- name: create requested repositories
  ansible.builtin.command: svnadmin create {{ subversion_path }}/{{ item.name }}
  args:
    creates: "{{ subversion_path }}/{{ item.name }}"
  loop: "{{ subversion_repositories }}"
  when:
    - subversion_repositories is defined
