---
# tasks file for subversion
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install subversion
  package:
    name: "{{ subversion_packages }}"
    state: present

- name: create requested repositories
  command: svnadmin create {{ subversion_path }}/{{ item.name }}
  args:
    creates: "{{ subversion_path }}/{{ item.name }}"
  loop: "{{ subversion_repositories }}"
  when:
    - subversion_repositories is defined
